//  here can be the answer from the server
const CATALOG = [{
    id: 'element1',
    image: './img/image_1.png',
    name: "Sportif's Original Short",
    star: 4,
    price: 67.00,
    color: './img/color_choose_1.png',
},
{
    id: 'element2',
    image: './img/image_2.png',
    name: "Sportif's Hatteras Short",
    star: 3,
    price: 54.99,
    color: './img/color_choose_2.png',
},
{
    id: 'element3',
    image: './img/image_3.png',
    name: "Sportif's Tidewater Short",
    star: 2,
    price: 54.99,
    color: './img/color_choose_3.png',
},
{
    id: 'element4',
    image: './img/image_4.png',
    name: "Sportif's Lauderdale Short",
    star: 1,
    price: 67.00,
    color: './img/color_choose_4.png',
},
{
    id: 'element5',
    image: './img/image_5.png',
    name: "Captain's Short",
    star: 5,
    price: 67.00,
    color: './img/color_choose_5.png',
},
{
    id: 'element6',
    image: './img/image_6.png',
    name: "Galapagos Plain Short",
    star: 5,
    price: 34.99,
    color: './img/color_choose_6.png',
},
{
    id: 'element7',
    image: './img/image_7.png',
    name: "Galapagos Pleated Short",
    star: 5,
    price: 34.99,
    color: './img/color_choose_7.png',
},
{
    id: 'element8',
    image: './img/image_8.png',
    name: "Sportif's Tidewater Denim Cargo Short",
    star: 5,
    price: 69.00,
    color: './img/color_choose_8.png',
},
{
    id: 'element9',
    image: './img/image_9.png',
    name: "Marchal's Hatteras Short",
    star: 5,
    price: 40.99,
    color: './img/color_choose_9.png',
},
{
    id: 'element10',
    image: './img/image_10.png',
    name: "Ecoths Ashcroft Short",
    star: 5,
    price: 41.99,
    color: './img/color_choose_10.png',
},
{
    id: 'element11',
    image: './img/image_11.png',
    name: "Ecoths Gannon Short",
    star: 2,
    price: 42.99,
    color: './img/color_choose_11.png',
}
];